server:
  port: 8090
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd hh:mm:ss
  #mysql
  datasource:
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowMultiQueries=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #druid
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 10
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      #exception-sorter: true
      pool-prepared-statements: true
      #      filters: stat,wall,slf4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      stat-view-servlet:
        login-username: industrial
        login-password: industrial123456
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.lce.common.domain